[[Libiconv]]
arch = "i686"
git-tree-sha1 = "9200a5f2cf3722f052aa50953aea0169bf1bfa36"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "2d2dfc0ef750078f3178309c66315e5ca1f795ccfc23abfc53dbbb3e4de92fab"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.i686-linux-gnu.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "bdc470dd53f10f62c9718c114b5eb177ef0ea221"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "e705516db8d8d22018afb62eb3049988fc40508463d9ccfc3bda93b86b3099c5"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.i686-linux-musl.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "ed6a34477068cf0defb98b2e16a434a9ef77b27c"
os = "macos"

    [[Libiconv.download]]
    sha256 = "23ecf387d885774b9bff8308c383c63b647d8322777ccb43b0f205dd22f1611f"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.x86_64-apple-darwin14.tar.gz"
[[Libiconv]]
arch = "powerpc64le"
git-tree-sha1 = "71af22402d10a0320a32adb95b3a017cfc0709ab"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "5f4b27dcc94237806771c410a1db0d3a1cf1386dde210ef4c86fdce122d0f5ac"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.powerpc64le-linux-gnu.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "2e7ba9af7f699054fc5c616a03099891f4bb98ac"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "8d5ed99d8aaeea07b2534d04949fa655abfa5726ab765df91768c93125a6e6ea"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.aarch64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "cfa9f74484967f0e50e4124bce3e68f3fd7bd936"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "8dceae9367c8997a3fa0b5c9c01ac7f74f244326d68d67997424a0b4ecb0dd96"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.x86_64-linux-musl.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "aa0ab6874b3c826f57822ef5b50473e9415fc12d"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "9e2bdd14925fc116f6ab5f1dd66b20e7170e6e994e8c7d6ca0bccb5b07c1f6d6"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.aarch64-linux-musl.tar.gz"
[[Libiconv]]
arch = "armv7l"
git-tree-sha1 = "2e16f7bfa0cf51ef26f6dd1ea2f58d2671a4173a"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "f805210af0009f8fe3dbad3ded9348ac3ed3e644352708338664df5591adc387"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.arm-linux-musleabihf.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "fb2ebe23e5ccc09d5085cd579022b7be38723b98"
os = "windows"

    [[Libiconv.download]]
    sha256 = "a7a1e7ce988aa637bad01723b9638971a54c0d37b6c1660e7fbf9d14f1416a15"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.i686-w64-mingw32.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "22439cc29ff8db1fa8250b9671b47ddd806afc37"
os = "freebsd"

    [[Libiconv.download]]
    sha256 = "db22abf155ee8b079fafb19b5eb08b8417d84ff1481323eb40390a012f31a615"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libiconv]]
arch = "armv7l"
git-tree-sha1 = "e664e5de938f1adf8992b552257b3ab2cc9cab1b"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "6e4bca98a69df36d77296a8d0e44df4e0861f30151f7348cadee968e038c646e"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.arm-linux-gnueabihf.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "f83fca02aa4a4d0b8aff38dc797d0e7aca0cea5b"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "ec088f395f7b14448d761783aac9e502bcea0721d4463aaae64db271daf87c89"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.x86_64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "473e9cc69e555bdf7dc23e9bbd724c5c693c1ea5"
os = "windows"

    [[Libiconv.download]]
    sha256 = "a905811a361dd2fcb1f50946f3dd167fad18de6de5712b329886f23e33eb1351"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+1/Libiconv.v1.16.0.x86_64-w64-mingw32.tar.gz"
