[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "b376941014acf8e5501996cdf9932036cfb3bb71"
os = "macos"

    [[Libiconv.download]]
    sha256 = "e480e9c26d51c89eab7ac5923d26c06b3e62e948b844a52c1542d562349f8e10"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.aarch64-apple-darwin.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "81959e09188a6041bc2d3570f8d3dea35291be72"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "d12c9a4c8f904eeca64c09d7edd785c20a28f7e1064a02a2280750ee3a19947c"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.aarch64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "40884a2c6af0718aa75aae865afa956dcc1829b0"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "327a0e80bfaa177f7e03588f0c5df0ba2d91777091f5a3604a000be6bbf4eaed"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.aarch64-linux-musl.tar.gz"
[[Libiconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "26b384ca0c0bdc8fa954b7e2dc3511c641e120b3"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "31264853f077e58fb5feda0b919bae80a49df8a742107e1be906513dced14872"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.armv6l-linux-gnueabihf.tar.gz"
[[Libiconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3400fe6c671f7265bca9b522956bb57f192ec74"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "c8b07db45fa259f6c87bc418d0ba4de61d4fe2a6b7330f5078ab5c61a79b0ca3"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.armv6l-linux-musleabihf.tar.gz"
[[Libiconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85afc1e2d3f33a1cb8bc73f89f041944d75d6a11"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "9682397802d8aad8a2b68df2638c93986c62bc394833ff49595c5af38eb6a296"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.armv7l-linux-gnueabihf.tar.gz"
[[Libiconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da82f2b4d463da4246826d57f3226a00f2f0012e"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "029b5059c0052d03f6b9f8c9fcac44b0a674356e803ee71c0bef129f536d50fe"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.armv7l-linux-musleabihf.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "a6d653ebe886c188a1a8110cb506084390840c8d"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "47470896b63fdfec019d95979680bf6301fe799fb97f8a6095c678ef66f02560"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.i686-linux-gnu.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "23197b8e6e023ac104f03e64992990eea6837dae"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "447f9fd74f9040e33cd97342c72ee6f3b306c65c0cb2f27b9d487465b50bf005"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.i686-linux-musl.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "b5d996ca47c4f6ef513a2427ac71d36313703d4f"
os = "windows"

    [[Libiconv.download]]
    sha256 = "899e260fe54bdb48e5e01c1603fc55293ec5ee4a61a5a153c73bb1580434b764"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.i686-w64-mingw32.tar.gz"
[[Libiconv]]
arch = "powerpc64le"
git-tree-sha1 = "d6e4b9261fd0d0f5bf5ae2aa89dbf7b0d519f531"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "4b6ced783ce5bb26092c3ccda7acca18db0d2d6c6d294d7e9568a69fd115eddb"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.powerpc64le-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "47a0441fc4c0611720643ad5cb10ad0fbf263c54"
os = "macos"

    [[Libiconv.download]]
    sha256 = "66d1afedc56708660420e179a3c0963bf49845e955ca7f8fbd7a4da8df1f06e5"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.x86_64-apple-darwin.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "e63503984ff7722ba80209eddd5621acca0d2d5e"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "5713372cba8664377c99247a2675ac8a794ce96911e07dc1c262c7c388459522"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.x86_64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "6da81b9ca6ca7c229d2e68f3efea30d4fe126fdd"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "69dc2533e9fbad1cd79f171746f7fd7968265ecea2529f460cc08b04a79f7fc2"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.x86_64-linux-musl.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "2a50aa632dd3445cf352b3133025eaa4d44ca296"
os = "freebsd"

    [[Libiconv.download]]
    sha256 = "a69706cb6bf2d8f0f74f15354a5b47b60d362df14eb852aae7b17244cf37355c"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.x86_64-unknown-freebsd.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "a5b7c195243758d88c64cd8547e527fbace3877b"
os = "windows"

    [[Libiconv.download]]
    sha256 = "0073db317676e6e098da476e4a446835453a49d66d1605328b0ff5d9d339e3aa"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+2/Libiconv.v1.16.1.x86_64-w64-mingw32.tar.gz"
