[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "06b4eca2da96ea8e2e910741b815dd66bbee8baa"
os = "macos"

    [[Libiconv.download]]
    sha256 = "3ba9da0cf5ed80742e7dcab93ee083de39360e76dc035bb97d5ff5de23f8e8e5"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.aarch64-apple-darwin.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "09e5a57af93fb36b5c0973c7d6f682182f928c92"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "9d1db641995495a7d959e0ff5be33631a3a9b856d589ca76e9043bd27be61772"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.aarch64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "3cf812916645cb6908ce6072207def3b86711976"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "2ce82c4980429cf200c450887a21316b658f33592d29c58f18f6e2b65292d893"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.aarch64-linux-musl.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "ce77625335b6067ee058f2393bfbdd6a81b51f3c"
os = "freebsd"

    [[Libiconv.download]]
    sha256 = "c171ae66e6d30827cdd3a482574ef332832b372b5d9098ab318d3d8d76c59162"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.aarch64-unknown-freebsd.tar.gz"
[[Libiconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b18c5ce060b1f9c4d427127738b4a0edcc09277e"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "1df31287c9f1d4b2517597f38525c9fad203da92f67fec775846981a12afeda1"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.armv6l-linux-gnueabihf.tar.gz"
[[Libiconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68aa28e32c77f9e0f172fbaa01e2515105fe2112"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "7dcd840381fab43bf1491e59b786de5c0a15997fad188ac52f89378099ba57ed"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.armv6l-linux-musleabihf.tar.gz"
[[Libiconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4e44f4cdd4286813d6443d428eb23c5042e39b4"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "3ed25ca0c9dda0f08f528f866ad9eb6796f3a28d9b1a4ebac56f46358c139301"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Libiconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72b4703862fc34eea5f01a040e918ac225bf7822"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "5d181d915b0a1e26155dc7526353f4366748e0f93e3c8a2c3f81441f71d346fb"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.armv7l-linux-musleabihf.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "20d2f17b7d13d5f6e6980ee841f725d78a950bda"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "49e9ddc4b0442eca0c9ae0f1f987ad403f0abc5510e42b752adf98a2263707ae"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.i686-linux-gnu.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "35827db6ebd5eee117ace86ff3af6af41aa885d9"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "e3b43ea617efc009ca0ae7407c8a1cfd4c21d51db75eb4163f282655592fb793"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.i686-linux-musl.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "577463ce50a47540a2cbb4c24673d52c755f0ab4"
os = "windows"

    [[Libiconv.download]]
    sha256 = "849b36d3f3ae9e9def775b4d655c0cbec1dd3e3f521f12390dac07f9636359b6"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.i686-w64-mingw32.tar.gz"
[[Libiconv]]
arch = "powerpc64le"
git-tree-sha1 = "e61a278f15a78cf79477d7fc85d809318a2b0a4e"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "d9afa2e7cb530b3ff413ab99cb0c67009239f458c85522cc248434508c0b906b"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.powerpc64le-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "b5c64ea2c07f56e11e857a5bc79886ceadb32338"
os = "macos"

    [[Libiconv.download]]
    sha256 = "97cf3c2b016417a1c79232db06f600b44e19b73a5444ae40542f79f1dbce17a7"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.x86_64-apple-darwin.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "2def0eca464bd6d89ccac85338474402359d4930"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "c545dd67dfd605a44bf45fc3cd8557202e13684fbbe759ae597a22a16967a7c6"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.x86_64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "1780861db2e56412e8b95b430953111a6faf1ffd"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "df0859bfe6bbe2110bf96a8e3e76653f29739bdf34b1efaa673a833831b9ccb0"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.x86_64-linux-musl.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "5e86c1830178986d4fa4bf90f629b4068260a62b"
os = "freebsd"

    [[Libiconv.download]]
    sha256 = "96141ccb935be7988b4385a83b596d2f4d4522032949c8b147b18fce9aab859c"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.x86_64-unknown-freebsd.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "79e4bc6534ea5a11e42eaf15947a2272949e4865"
os = "windows"

    [[Libiconv.download]]
    sha256 = "e9c6402b9e339f15c6c211e366d30ba9e80ae7a745b1c94ed8b4f4f3caecc086"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.17.0+1/Libiconv.v1.17.0.x86_64-w64-mingw32.tar.gz"
